/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestedRouteImport } from './routes/_guested'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedTransactionsIndexRouteImport } from './routes/_authed/transactions/index'
import { Route as AuthedPocketsIndexRouteImport } from './routes/_authed/pockets/index'
import { Route as GuestedAuthLoginRouteImport } from './routes/_guested/auth/login'
import { Route as GuestedAuthCallbackRouteImport } from './routes/_guested/auth/callback'
import { Route as AuthedTransactionsNewRouteImport } from './routes/_authed/transactions/new'
import { Route as AuthedPocketsNewRouteImport } from './routes/_authed/pockets/new'
import { Route as AuthedTransactionsIdRouteRouteImport } from './routes/_authed/transactions/$id/route'
import { Route as AuthedTransactionsIdIndexRouteImport } from './routes/_authed/transactions/$id/index'
import { Route as AuthedPocketsIdIndexRouteImport } from './routes/_authed/pockets/$id/index'
import { Route as AuthedTransactionsIdEditRouteImport } from './routes/_authed/transactions/$id/edit'
import { Route as AuthedPocketsIdEditRouteImport } from './routes/_authed/pockets/$id/edit'

const GuestedRoute = GuestedRouteImport.update({
  id: '/_guested',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIndexRoute = AuthedTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPocketsIndexRoute = AuthedPocketsIndexRouteImport.update({
  id: '/pockets/',
  path: '/pockets/',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestedAuthLoginRoute = GuestedAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => GuestedRoute,
} as any)
const GuestedAuthCallbackRoute = GuestedAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => GuestedRoute,
} as any)
const AuthedTransactionsNewRoute = AuthedTransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPocketsNewRoute = AuthedPocketsNewRouteImport.update({
  id: '/pockets/new',
  path: '/pockets/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIdRouteRoute =
  AuthedTransactionsIdRouteRouteImport.update({
    id: '/transactions/$id',
    path: '/transactions/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTransactionsIdIndexRoute =
  AuthedTransactionsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedTransactionsIdRouteRoute,
  } as any)
const AuthedPocketsIdIndexRoute = AuthedPocketsIdIndexRouteImport.update({
  id: '/pockets/$id/',
  path: '/pockets/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIdEditRoute =
  AuthedTransactionsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedTransactionsIdRouteRoute,
  } as any)
const AuthedPocketsIdEditRoute = AuthedPocketsIdEditRouteImport.update({
  id: '/pockets/$id/edit',
  path: '/pockets/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/transactions/$id': typeof AuthedTransactionsIdRouteRouteWithChildren
  '/pockets/new': typeof AuthedPocketsNewRoute
  '/transactions/new': typeof AuthedTransactionsNewRoute
  '/auth/callback': typeof GuestedAuthCallbackRoute
  '/auth/login': typeof GuestedAuthLoginRoute
  '/pockets/': typeof AuthedPocketsIndexRoute
  '/transactions/': typeof AuthedTransactionsIndexRoute
  '/pockets/$id/edit': typeof AuthedPocketsIdEditRoute
  '/transactions/$id/edit': typeof AuthedTransactionsIdEditRoute
  '/pockets/$id/': typeof AuthedPocketsIdIndexRoute
  '/transactions/$id/': typeof AuthedTransactionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/pockets/new': typeof AuthedPocketsNewRoute
  '/transactions/new': typeof AuthedTransactionsNewRoute
  '/auth/callback': typeof GuestedAuthCallbackRoute
  '/auth/login': typeof GuestedAuthLoginRoute
  '/pockets': typeof AuthedPocketsIndexRoute
  '/transactions': typeof AuthedTransactionsIndexRoute
  '/pockets/$id/edit': typeof AuthedPocketsIdEditRoute
  '/transactions/$id/edit': typeof AuthedTransactionsIdEditRoute
  '/pockets/$id': typeof AuthedPocketsIdIndexRoute
  '/transactions/$id': typeof AuthedTransactionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_guested': typeof GuestedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/_authed/transactions/$id': typeof AuthedTransactionsIdRouteRouteWithChildren
  '/_authed/pockets/new': typeof AuthedPocketsNewRoute
  '/_authed/transactions/new': typeof AuthedTransactionsNewRoute
  '/_guested/auth/callback': typeof GuestedAuthCallbackRoute
  '/_guested/auth/login': typeof GuestedAuthLoginRoute
  '/_authed/pockets/': typeof AuthedPocketsIndexRoute
  '/_authed/transactions/': typeof AuthedTransactionsIndexRoute
  '/_authed/pockets/$id/edit': typeof AuthedPocketsIdEditRoute
  '/_authed/transactions/$id/edit': typeof AuthedTransactionsIdEditRoute
  '/_authed/pockets/$id/': typeof AuthedPocketsIdIndexRoute
  '/_authed/transactions/$id/': typeof AuthedTransactionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/transactions/$id'
    | '/pockets/new'
    | '/transactions/new'
    | '/auth/callback'
    | '/auth/login'
    | '/pockets/'
    | '/transactions/'
    | '/pockets/$id/edit'
    | '/transactions/$id/edit'
    | '/pockets/$id/'
    | '/transactions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/$'
    | '/pockets/new'
    | '/transactions/new'
    | '/auth/callback'
    | '/auth/login'
    | '/pockets'
    | '/transactions'
    | '/pockets/$id/edit'
    | '/transactions/$id/edit'
    | '/pockets/$id'
    | '/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guested'
    | '/_authed/dashboard'
    | '/api/$'
    | '/_authed/transactions/$id'
    | '/_authed/pockets/new'
    | '/_authed/transactions/new'
    | '/_guested/auth/callback'
    | '/_guested/auth/login'
    | '/_authed/pockets/'
    | '/_authed/transactions/'
    | '/_authed/pockets/$id/edit'
    | '/_authed/transactions/$id/edit'
    | '/_authed/pockets/$id/'
    | '/_authed/transactions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestedRoute: typeof GuestedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guested': {
      id: '/_guested'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/': {
      id: '/_authed/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedTransactionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pockets/': {
      id: '/_authed/pockets/'
      path: '/pockets'
      fullPath: '/pockets/'
      preLoaderRoute: typeof AuthedPocketsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guested/auth/login': {
      id: '/_guested/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestedAuthLoginRouteImport
      parentRoute: typeof GuestedRoute
    }
    '/_guested/auth/callback': {
      id: '/_guested/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof GuestedAuthCallbackRouteImport
      parentRoute: typeof GuestedRoute
    }
    '/_authed/transactions/new': {
      id: '/_authed/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthedTransactionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pockets/new': {
      id: '/_authed/pockets/new'
      path: '/pockets/new'
      fullPath: '/pockets/new'
      preLoaderRoute: typeof AuthedPocketsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/$id': {
      id: '/_authed/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthedTransactionsIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/$id/': {
      id: '/_authed/transactions/$id/'
      path: '/'
      fullPath: '/transactions/$id/'
      preLoaderRoute: typeof AuthedTransactionsIdIndexRouteImport
      parentRoute: typeof AuthedTransactionsIdRouteRoute
    }
    '/_authed/pockets/$id/': {
      id: '/_authed/pockets/$id/'
      path: '/pockets/$id'
      fullPath: '/pockets/$id/'
      preLoaderRoute: typeof AuthedPocketsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/$id/edit': {
      id: '/_authed/transactions/$id/edit'
      path: '/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof AuthedTransactionsIdEditRouteImport
      parentRoute: typeof AuthedTransactionsIdRouteRoute
    }
    '/_authed/pockets/$id/edit': {
      id: '/_authed/pockets/$id/edit'
      path: '/pockets/$id/edit'
      fullPath: '/pockets/$id/edit'
      preLoaderRoute: typeof AuthedPocketsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedTransactionsIdRouteRouteChildren {
  AuthedTransactionsIdEditRoute: typeof AuthedTransactionsIdEditRoute
  AuthedTransactionsIdIndexRoute: typeof AuthedTransactionsIdIndexRoute
}

const AuthedTransactionsIdRouteRouteChildren: AuthedTransactionsIdRouteRouteChildren =
  {
    AuthedTransactionsIdEditRoute: AuthedTransactionsIdEditRoute,
    AuthedTransactionsIdIndexRoute: AuthedTransactionsIdIndexRoute,
  }

const AuthedTransactionsIdRouteRouteWithChildren =
  AuthedTransactionsIdRouteRoute._addFileChildren(
    AuthedTransactionsIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTransactionsIdRouteRoute: typeof AuthedTransactionsIdRouteRouteWithChildren
  AuthedPocketsNewRoute: typeof AuthedPocketsNewRoute
  AuthedTransactionsNewRoute: typeof AuthedTransactionsNewRoute
  AuthedPocketsIndexRoute: typeof AuthedPocketsIndexRoute
  AuthedTransactionsIndexRoute: typeof AuthedTransactionsIndexRoute
  AuthedPocketsIdEditRoute: typeof AuthedPocketsIdEditRoute
  AuthedPocketsIdIndexRoute: typeof AuthedPocketsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTransactionsIdRouteRoute: AuthedTransactionsIdRouteRouteWithChildren,
  AuthedPocketsNewRoute: AuthedPocketsNewRoute,
  AuthedTransactionsNewRoute: AuthedTransactionsNewRoute,
  AuthedPocketsIndexRoute: AuthedPocketsIndexRoute,
  AuthedTransactionsIndexRoute: AuthedTransactionsIndexRoute,
  AuthedPocketsIdEditRoute: AuthedPocketsIdEditRoute,
  AuthedPocketsIdIndexRoute: AuthedPocketsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestedRouteChildren {
  GuestedAuthCallbackRoute: typeof GuestedAuthCallbackRoute
  GuestedAuthLoginRoute: typeof GuestedAuthLoginRoute
}

const GuestedRouteChildren: GuestedRouteChildren = {
  GuestedAuthCallbackRoute: GuestedAuthCallbackRoute,
  GuestedAuthLoginRoute: GuestedAuthLoginRoute,
}

const GuestedRouteWithChildren =
  GuestedRoute._addFileChildren(GuestedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GuestedRoute: GuestedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
